---
name: pull-request

on: 
    pull_request:
        branches: 
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: get the code
              uses: actions/checkout@v6
            - name: install depdendencies
              run: npm install
            - name: run the build
              run: npm run build
            - name: run the tests
              run:  npm run test:report
            - name: publish test results
              uses: EnricoMi/publish-unit-test-result-action@v2
              with:
                files: "**/test-results/results.xml"
                comment_mode: always